apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-app
  namespace: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vulnerable-app
  template:
    metadata:
      labels:
        app: vulnerable-app
    spec:
      hostNetwork: true
      containers:
      - name: app
        image: myapp:latest
        securityContext:
          privileged: true
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
